#=================================Isaac Kakodwa==============================;==
from tkinter import*
import time
import sqlite3
from tkinter.messagebox import*
import tkinter.ttk as ttk
#================================main.main========================================
root=Tk()
root.geometry("1600x800+0+0")
root.title("IK-TECH/MANAGEMENT SYSTEM/")
#===============================table================================================
TRANSACTION = StringVar()
PRICE = IntVar()
AMOUNT=IntVar()
BALANCE=IntVar()
DATA=StringVar()

conn=sqlite3.connect("outflow.db")
cursor=conn.cursor()
cursor.execute("""CREATE TABLE IF NOT EXISTS out (trank TEXT,ptice INT,amount INT,balance INT,data TEXT)""")

def insert():
    if TRANSACTION.get() == "" or DATA.get()=="":
        showinfo("IK-TECH","Please complete the required field!!!!")
    else:
        conn=sqlite3.connect("outflow.db")
        cursor=conn.cursor()
        data="INSERT INTO out(trank ,ptice ,amount,balance ,data) VALUES (?,?,?,?,?)"
        cursor.execute(data,[TRANSACTION.get(),PRICE.get(),AMOUNT.get(),BALANCE.get(),DATA.get()])
        conn.commit()
        TRANSACTION.set("") 
        PRICE.set("")
        AMOUNT.set("")
        BALANCE.set("")
        DATA.set("")
        showinfo("IK-TECH","Data YANU yalowa mu system!!!")


#================================================inflow============================================
FIST_NAME= StringVar()
LAST_NAME=StringVar()
FON_NUMBER=StringVar()
TRASA=StringVar()
PRICE_TRAS=IntVar()
AMOUNT_PAID=IntVar()
BALANCE_TRASA=IntVar()
DATA_TRASA=StringVar()

db=sqlite3.connect("inflow.db")
cursor=db.cursor()
cursor.execute("""CREATE TABLE IF NOT EXISTS customer(first TEXT,last TEXT,fon TEXT,transa TEXT,price INT,paid INT,balance INT, data TEXT)""")

def insert_into():
    if FIST_NAME.get() == "" or LAST_NAME.get()=="":
        showinfo("IK-TECH","Please complete the required field!!!")
    else:
        db=sqlite3.connect("inflow.db")
        cursor=db.cursor()
        info="INSERT INTO customer (first,last ,transa ,fon ,price ,paid ,balance ,data ) VALUES(?,?,?,?,?,?,?,?)"
        cursor.execute(info,[FIST_NAME.get(),LAST_NAME.get(),FON_NUMBER.get(),TRASA.get(),PRICE_TRAS.get(),AMOUNT_PAID.get(),BALANCE_TRASA.get(),DATA_TRASA.get()])
        db.commit()
        FIST_NAME.set("")
        LAST_NAME.set("")
        FON_NUMBER.set("")
        TRASA.set("")
        PRICE_TRAS.set("")
        AMOUNT_PAID.set("")
        BALANCE_TRASA.set("")
        DATA_TRASA.set("")
        showinfo("IK-TECH","Data YANU yalowa mu system!!!")
#===============search============================================================
def DisplayData():
    db=sqlite3.connect("inflow.db")
    cursor=db.cursor()
    cursor.execute("SELECT * FROM `customer` ORDER BY `last` ASC")
    fetch = cursor.fetchall()
    for data in fetch:
        tree.insert('', 'end', values=(data))
    cursor.close()
    conn.close()
SEARCH=StringVar()
def Search():
    if SEARCH.get() == "":
        showinfo("IK-TECH","Please complete the required field!!!")
    
    else:
        db=sqlite3.connect("inflow.db")
        cursor=db.cursor()
        sq="SELECT * FROM `customer` WHERE `last` LIKE ?"
        cursor.execute(sq,[SEARCH.get()])
        fetch = cursor.fetchall()
        for data in fetch:
            tree.insert('', 'end', values=(data))
            cursor.close()
            conn.close()
            SEARCH.set("")

def Reset():
    tree.delete(*tree.get_children())
        
#==============methods================================================
def exit():
    warning = askyesno("Warning","Are you serious you want to Quit?")
    if warning > 0:
        root.destroy()
app = ("Business Management Sysstem.\nThis app is Not For Sale\nDeveloped by ISAAC KAKODWA."
      "\n2018 All Rights Reserved.\n@Ikpixels.Inc\n\n\n\n --Python--")
def secondtroot():
    win=Toplevel()
    win.geometry("500x300+0+0")
    win.title("ABOUT APP")
    win.config(background = 'light blue')
    la1=Label(win, bg ='light blue', font = ('times', 20, 'italic'), text = app)
    la1.pack()
def clint_info():
    def find():
        db=sqlite3.connect("outflow.db")
        cursor=db.cursor()
        sq="SELECT * FROM `out`"
        cursor.execute(sq)
        fetch = cursor.fetchall()
        for data in fetch:
            tree1.insert('', 'end', values=(data))
            cursor.close()
            conn.close()
          
    client = Toplevel()
    client.geometry("800x600+0+0")
    client.title("INFLOW INFORMATION")
    btn=Button(client, text="View Data",font=('times', 15,'bold'), fg= 'blue',command=find,bd=0)
    btn.place(x= 30, y = 300)
    fa= Frame(client, height= 550, width=500, bg = 'skyblue', bd= 8, relief='raised')
    fa.place(x=150, y=15)
    yscrollbar=Scrollbar(fa,orient=VERTICAL)
    xscrollbar=Scrollbar(fa,orient=HORIZONTAL)
    tree1=ttk.Treeview(fa, column=("trank" ,"ptice" ,"amount","balance" ,"data"),selectmode="extended", height=25, yscrollcommand=scrollbary.set, xscrollcommand=scrollbarx.set)
    scrollbary.config(command=tree1.yview)
    scrollbary.pack(side=RIGHT, fill=Y)
    scrollbarx.config(command=tree1.xview)
    scrollbarx.pack(side=BOTTOM, fill=X)
    tree1.heading('trank', text= 'Item', anchor = W)
    tree1.heading('ptice', text= 'Cost', anchor = W)
    tree1.heading('amount', text= 'Principal', anchor = W)
    tree1.heading('balance', text= 'Balance', anchor = W)
    tree1.heading('data', text= 'Date', anchor = W)
    tree1.column('#0',stretch=0,minwidth=0,width=70)
    tree1.column('#1',stretch=0,minwidth=0,width=70)
    tree1.column('#2',stretch=0,minwidth=0,width=70)
    tree1.column('#3',stretch=0,minwidth=0,width=70)
    tree1.column('#4',stretch=0,minwidth=0,width=70)
    tree1.pack()
def others():
    cal=Toplevel(root)
    cal.geometry("800x500+0+0")
    cal.title("anuuity")

def amortiza():
    LOAN=IntVar()
    RATE=IntVar()
    TIME=IntVar()

    def pmt():
        if LOAN.get()==0 or TIME.get()==0:
            showinfo("IK-TECH","Please first fill the required fields")
        else:
            p=LOAN.get()
            r=RATE.get()
            t=TIME.get()
            outcome=((p*((r/100)/12)*(1+((r/100)/12))**(12*t))/(((1+((r/100)/12))**(12*t))-1))
            Intrest=(((12*t)*outcome)-p)
            textm.insert(END,"The monthly \n payment is K")
            textm.insert(END,round(outcome))
            textm.insert(END,"\n\n")
            textm.insert(END,"Total intrest paid to the lender is K")
            textm.insert(END,round(Intrest))
            LOAN.set("")
            RATE.set("")
            TIME.set("")
    def deti():
        LOAN.set("")
        RATE.set("")
        TIME.set("")
        textm.delete("0.1",END)
    mo=Toplevel(root)
    mo.geometry("600x500+0+0")
    mo.title("Amortization")
    mo.config(background="skyblue")
    m1=Label(mo,text="Full Loan....................",font=('times',20,'bold'), bg='skyblue')
    m1.place(x=5,y=20)
    m2=Label(mo,text="RATE(%).................",font=('times',20,'bold'), bg='skyblue')
    m2.place(x=5,y=65)
    m3=Label(mo,text="TIME(years).............",font=('times',20,'bold'), bg='skyblue')
    m3.place(x=5,y=110)
    mo1=Entry(mo,width=20,font=('times',20,'bold'),bd=2,textvariable=LOAN)
    mo1.place(x=250,y=20)
    mo2=Entry(mo,width=20, font=('times',20,'bold'),textvariable=RATE)
    mo2.place(x=250,y=65)
    mo3=Entry(mo,width=20, font=('times',20,'bold'),textvariable=TIME)
    mo3.place(x=250,y=110)
    btn=Button(mo,text="Monthly Payment", fg='green', width=15,font=('arial',15,'bold'),command=pmt)
    btn.place(x=10,y=200)
    btn2=Button(mo,text="Reset", fg='green', width=15,font=('arial',15,'bold'),command=deti)
    btn2.place(x=10,y=245)
    textm=Text(mo,bd=3,width=18,height=8,font=('arial',20,'bold'))
    textm.place(x=250,y=200)
    la=Label(mo,text="AMORTIZATION",font=('arial',20,'bold'),bg='skyblue')
    la.place(x=10,y=400)

def money():
    PV=IntVar()
    FV=IntVar()
    RATE=IntVar()
    TIME=IntVar()

    def pv():
        if RATE.get()==0 or TIME.get()==0:
            showinfo("IK-TECH","Please first fill the required fields")
        else:
            f=FV.get()
            r=RATE.get()
            t=TIME.get()
            result=(f/((1+(r/100))**t))
            tex1.insert(END,"Present value of money"+"\n")
            tex1.insert(END," "+"is K" )
            tex1.insert(END,result)
            PV.set("")
            FV.set("")
            RATE.set("")
            TIME.set("")

    def fv():
        if RATE.get()==0 or TIME.get()==0:
            showinfo("IK-TECH","Please first fill the required fields")
        else:
            p=PV.get()
            r=RATE.get()
            t=TIME.get()
            out=(p*((1+(r/100))**t))
            tex1.insert(END,"Worth of savings " +"after "+" ")
            tex1.insert(END,t)
            tex1.insert(END," "+ "year will be "+"K" )
            tex1.insert(END,out)
            PV.set("")
            FV.set("")
            RATE.set("")
            TIME.set("")
    def futa():
        PV.set("")
        FV.set("")
        RATE.set("")
        TIME.set("")
        tex1.delete("0.1",END)
 
    cal=Toplevel(root)
    cal.geometry("600x500+0+0")
    cal.title("Value of money")
    cal.config(background="black")
    ml1=Label(cal,text="Present Value(PV).............", font=('times',20,'bold'),fg='skyblue',bg='black')
    ml1.place(x=5,y=20)
    ml2=Label(cal,text="Future Value(FV)............", font=('times',20,'bold'),fg='green',bg='black')
    ml2.place(x=5,y=65)
    ml3=Label(cal,text="Number of Years(t).............", font=('times',20,'bold'),fg='white',bg='black')
    ml3.place(x=5,y=110)
    ml3=Label(cal,text="Intrest Rate(r%)...............", font=('times',20,'bold'),fg='white',bg='black')
    ml3.place(x=5,y=155)
    me1=Entry(cal,width=20,font=('times',20,'bold'),bd=2,textvariable=PV)
    me1.place(x=300,y=20)
    me2=Entry(cal,width=20, font=('times',20,'bold'),textvariable=FV)
    me2.place(x=300,y=65)
    me3=Entry(cal,width=20, font=('times',20,'bold'),textvariable=TIME)
    me3.place(x=300,y=110)
    me3=Entry(cal,width=20, font=('times',20,'bold'),textvariable=RATE)
    me3.place(x=300,y=155)
    mf1=Frame(cal,width=600,height=50,bg='black')
    mf1.place(x=0,y=200)
    ml4=Label(mf1,text="TIME VALUE OF MONEY", font=('arial',20,'bold'),fg='green',bg='black')
    ml4.place(x=110,y=15)
    btn=Button(cal,text="Present Value", bg= 'skyblue',font=('arial',15,'bold'),width=13,command=pv)
    btn.place(x=5,y=300)
    btn1=Button(cal,text="Future Value", bg= 'green',font=('arial',15,'bold'),width=13,command=fv)
    btn1.place(x=5,y=350)
    btn2=Button(cal,text="Reset", bg= 'white',font=('arial',15,'bold'),width=13,command=futa)
    btn2.place(x=5,y=400)
    tex1=Text(cal,bd=3,width=25,height=4,font=('times',20,'bold'))
    tex1.place(x=200,y=300)
    kk=Label(cal,text='IK-TECH',fg='green',font=('arial',15,'italic'),bg ='black',bd=5)
    kk.place(x=10,y=460)
#================================text 1==============================================
text1 = Frame (root, height=500, width = 400, bg='skyblue', bd = 8)
text1.place(x=400, y = 100)
#=================================top frame===========================================
f1= Frame(root, height = 80, width= 1355, bg = 'black',relief = 'sunken', bd = 30 )
f1.place(x = 1.4 , y = 15)
#==================================task bar===========================================
f2= Frame(root, height = 50, width= 1355, bg = 'black',relief = 'sunken', bd = 5 )
f2.place(x = 1.4 , y = 660)
ik=Label(f2,text='IK-TECH',fg='green',font=('arial',15,'italic'),bg ='black',bd=5)
ik.place(x=10,y=5)
k=Label(f2,text='TIME :',fg='green',font=('arial',10,'italic'),bg ='black',bd=5)
k.place(x=1100,y=5)
#=================================label inflow========================================
l1= Label(root, text = "First name:", fg= 'black', font = ( 'time', 15 , 'bold'))
l1.place(x=1, y=100)
l2= Label(root, text = "Last name:", fg= 'black', font = ( 'time', 15 , 'bold'))
l2.place(x=1, y=150)
l3= Label(root, text = "Phone number:", fg= 'black', font = ( 'time', 15 , 'bold'))
l3.place(x=1, y=200)
l4= Label(root, text = "Item:", fg= 'black', font = ( 'time', 15 , 'bold'))
l4.place(x=1, y=250)
l5= Label(root, text = "Price", fg= 'black', font = ( 'time', 15 , 'bold'))
l5.place(x=1, y=300)
l6= Label(root, text = "Deposit:", fg= 'black', font = ( 'time', 15 , 'bold'))
l6.place(x=1, y=350)
l7= Label(root, text = "Balance:", fg= 'black', font = ( 'time', 15 , 'bold'))
l7.place(x=1, y=400)
l8= Label(root, text = "Date:", fg= 'black', font = ( 'time', 15 , 'bold'))
l8.place(x=1, y=450)
#==============================entry 1================================================
e1= Entry(root, font = ( 'time', 15 ), width = 20, bd =5, textvariable=FIST_NAME )
e1.place(x=150, y=100)
e2= Entry(root,  font = ( 'time', 15 ), width = 20, bd =5,textvariable=LAST_NAME)
e2.place(x=150, y=150)
e3= Entry(root, font = ( 'time', 15 ), width = 20, bd =5,textvariable=FON_NUMBER)
e3.place(x=150, y=200)
e4= Entry(root, font = ( 'time', 15 ), width = 20, bd =5,textvariable=TRASA)
e4.place(x=150, y=250)
e5= Entry(root, font = ( 'time', 15 ), width = 20, bd =5,textvariable=PRICE_TRAS)
e5.place(x=150, y=300)
e6= Entry(root, font = ( 'time', 15 ), width = 20, bd =5,textvariable=AMOUNT_PAID)
e6.place(x=150, y=350)
e7= Entry(root,  font = ( 'time', 15 ), width = 20, bd =5,textvariable=BALANCE_TRASA)
e7.place(x=150, y=400)
e8= Entry(root,  font = ( 'time', 15 ), width = 20, bd =5,textvariable=DATA_TRASA)
e8.place(x=150, y=450)
e9 = Entry(root,  font = ( 'time', 15 ), width = 20, bd =5, textvariable=SEARCH)
e9.place(x=150, y=560)
#==============================entry 2================================================
ee1= Entry(root,font = ( 'time', 15 ), width = 20, bd =5,textvariable=TRANSACTION  )
ee1.place(x=1100, y=100)
ee2=  Entry(root, font = ( 'time', 15 ), width = 20, bd =5,textvariable=PRICE )
ee2.place(x=1100, y=150)
ee3=  Entry(root,font = ( 'time', 15 ), width = 20, bd =5 ,textvariable=AMOUNT)
ee3.place(x=1100, y=200)
ee4=  Entry(root,font = ( 'time', 15 ), width = 20, bd =5,textvariable=BALANCE )
ee4.place(x=1100, y=250)
ee5=  Entry(root,font = ( 'time', 15 ), width = 20, bd =5,textvariable=DATA)
ee5.place(x=1100, y=300)
#===========================labels 2=======================================================
ll1= Label(root, text = "Item:", fg= 'black', font = ( 'time', 15 , 'bold'))
ll1.place(x=920, y=100)
ll2= Label(root, text = "Cost:", fg= 'black', font = ( 'time', 15 , 'bold'))
ll2.place(x=920, y=150)
ll3= Label(root, text = "Principal:", fg= 'black', font = ( 'time', 15 , 'bold'))
ll3.place(x=920, y=200)
ll4= Label(root, text = "Balance:", fg= 'black', font = ( 'time', 15 , 'bold'))
ll4.place(x=920, y=250)
ll5= Label(root, text = "Date:", fg= 'black', font = ( 'time', 15 , 'bold'))
ll5.place(x=920, y=300)
#=========================button 1/========================================================
btn1= Button(root, text='INSERT',relief= 'raised', width= 29 ,bd = 10, fg = 'blue', command=insert_into)
btn1.place( x= 150, y = 500)
btn2= Button(root, text='INSERT',relief= 'raised', width= 29 ,bd = 10, fg = 'blue', command=insert)
btn2.place( x= 1100, y = 350)
btn8= Button(root, text='Search Client',width= 18,relief= 'raised' ,bd = 5, fg = 'green',font = ( 'time', 8 , 'bold'),command=Search)
btn8.place( x= 1, y = 560)
btn9= Button(root, text='View Data',width= 18,relief= 'raised' ,bd = 5, fg = 'green',font = ( 'time', 8 , 'bold'), command=DisplayData)
btn9.place( x= 1, y = 620)
btn9= Button(root, text='Reset',width= 18,relief= 'raised' ,bd = 5, fg = 'green',font = ( 'time', 8 , 'bold'),command=Reset )
btn9.place( x= 150, y = 620)
btn10= Button(root, text='Delete',width= 10,relief= 'raised' ,bd = 5, fg = 'green',font = ( 'time', 8 , 'bold'),)
btn10.place( x= 300, y = 620)
#==========================menu==============================================================
menubar = Menu(root)
filemenu = Menu(menubar, tearoff=0)
filemenu2 = Menu(menubar, tearoff=0)
filemenu3 = Menu(menubar, tearoff=0)
filemenu.add_command(label="about", command=secondtroot)
filemenu.add_command(label="Exit",command=exit)
filemenu2.add_command(label="Inflow")
filemenu2.add_command(label="OutFlow")
filemenu2.add_command(label="Inventory")
filemenu2.add_command(label="Annuities", command=others)
filemenu2.add_command(label="Amortization",command=amortiza)
filemenu2.add_command(label="Value Of Money",command=money)
filemenu3.add_command(label="Details", command=clint_info)
menubar.add_cascade(label="File", menu=filemenu)
menubar.add_cascade(label="Calculation", menu=filemenu2)
menubar.add_cascade(label="OutFlowInfo", menu=filemenu3)
root.config(menu=menubar)
#==============================scrollbar======================================================
scrollbary = Scrollbar(text1, orient=VERTICAL)
scrollbarx = Scrollbar(text1, orient=HORIZONTAL)
tree = ttk.Treeview(text1, columns=("first","last" ,"transa" ,"fon" ,"price" ,"paid" ,"balance" ,"data"), selectmode="extended", height=24, yscrollcommand=scrollbary.set, xscrollcommand=scrollbarx.set)
scrollbary.config(command=tree.yview)
scrollbary.pack(side=RIGHT, fill=Y)
scrollbarx.config(command=tree.xview)
scrollbarx.pack(side=BOTTOM, fill=X)
tree.heading('first', text="FirstName", anchor=W)
tree.heading('last', text="LastName", anchor=W)
tree.heading('transa', text="Item", anchor=W)
tree.heading('fon', text="Phone", anchor=W)
tree.heading('price', text="Price", anchor=W)
tree.heading('paid', text="Deposite", anchor=W)
tree.heading('balance', text="Balance", anchor=W)
tree.heading('data', text="Date", anchor=W)
tree.column('#0', stretch=NO, minwidth=0, width=0)
tree.column('#1', stretch=NO, minwidth=0, width=70)
tree.column('#2', stretch=NO, minwidth=0, width=70)
tree.column('#3', stretch=NO, minwidth=0, width=70)
tree.column('#4', stretch=NO, minwidth=0, width=50)
tree.column('#5', stretch=NO, minwidth=0, width=50)
tree.column('#6', stretch=NO, minwidth=0, width=60)
tree.column('#7', stretch=NO, minwidth=0, width=60)
tree.column('#8', stretch=NO, minwidth=0, width=50)
tree.pack()
#================================labels====================================================
ll= Label(f1, text ="|   CASH INFLOW   |", fg = 'white', font = ('arial', 10,'italic'), bg = 'black')
ll.place(x = 80, y = 2)
ll= Label(f1, text ="|   OUTPUT   |", fg = 'white', font = ('arial', 10,'italic'), bg = 'black')
ll.place(x = 580, y = 2)
ll= Label(f1, text ="|   CASH OUTFLOW   |", fg = 'white', font = ('arial', 10,'italic'), bg = 'black')
ll.place(x = 1000, y = 2)
#==================================time==================================================================
localtime = time.asctime(time.localtime(time.time()))
clock= Text(f2,width= 25,height= 1, bd = 5, font=('arial', 10,'bold'))
clock.place(x=1150, y = 5)
clock.insert(END,localtime)
le = Label(root,text ="*Input client last name*", fg = 'black', font = ('arial', 10,'bold') )
le.place(x = 180, y= 590)
#==================================tree=======================================================


root.mainloop()
